### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by NNemec** [Murazaki/QObjectListModel-QQuickList#5]
Without a license, this code cannot be used legally in any way. I would really like to use this class in our code. Ideal for such a small snippet would be a BSD license that allows anyone to copy the code into any project as long as the copyright notice is kept in place, and have no further hassle with it.

**Comment by Murazaki** [comment]
Thanks for the heads up. I'll look into it.

I might put it under a MIT License, is that ok for you ?
Also, can you give me some insights about what you're planning on using the code for ? Just for my personal curiosity :) (you can send me an e-mail, if you'd like).

**Comment by NNemec** [comment]
MIT License is just as good for me.
QQuickList seems to be just the generic component that I was missing in
QtQuick to quckly build up a QML interface. I have not yet investigated it
in depth, yet. Just wanted to make sure first that the license will not
cause any hassle in the future.

On Fri, Jun 24, 2016 at 2:58 PM, Mehdi Zakaria Benadel <
notifications@github.com> wrote:

> Thanks for the heads up. I'll look into it.
>
> I might put it under a MIT License, is that ok for you ?
> Also, can you give me some insights about what you're planning on using
> the code for ? Just for my personal curiosity :) (you can send me an
> e-mail, if you'd like).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Murazaki/QObjectListModel-QQuickList/issues/5#issuecomment-228338717>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAVHfnxzJXQmtGl5zGNmYLJKfDDLaaiTks5qO9R0gaJpZM4I9sk7>
> .
>



-- 
______________________________________________Norbert Nemec
        Aignerstr. 26 ... 81541 München ... Germany
      Tel: +49-89-18944209  Mobile: +49-176-5502 5643
             eMail:  <Norbert@Nemec-online.de> <Norbert@Nemec-online.de>

**Comment by Murazaki** [comment]
Here you are.

**Comment by NNemec** [comment]
Hi Mehdi,

just had another look at the code. One detail I noticed:
As I understand it, QObjectListModel::m_data always keeps a copy of the
items stored in the corresponding QQuickList. Right?
Wouldn't it be better to have QObjectListModel to keep a reference to the
QQuickList itself and keep the data only once?

Furthermore: QObjectListModel::setData seems to modify QObjectListModel::m_data
but not the QQuickList, so both lists will get out of sync.
Having just one data storage would avoid that problem.
QObjectListModel::setData
would then have to modify the QQuickList. To do so, it would require a cast
and fail if the QObject is of the wrong type.

On Fri, Jun 24, 2016 at 4:53 PM, Norbert Nemec Norbert@nemec-online.de
wrote:

> MIT License is just as good for me.
> QQuickList seems to be just the generic component that I was missing in
> QtQuick to quckly build up a QML interface. I have not yet investigated it
> in depth, yet. Just wanted to make sure first that the license will not
> cause any hassle in the future.
> 
> On Fri, Jun 24, 2016 at 2:58 PM, Mehdi Zakaria Benadel <
> notifications@github.com> wrote:
> 
> > Thanks for the heads up. I'll look into it.
> > 
> > I might put it under a MIT License, is that ok for you ?
> > Also, can you give me some insights about what you're planning on using
> > the code for ? Just for my personal curiosity :) (you can send me an
> > e-mail, if you'd like).
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/Murazaki/QObjectListModel-QQuickList/issues/5#issuecomment-228338717,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AAVHfnxzJXQmtGl5zGNmYLJKfDDLaaiTks5qO9R0gaJpZM4I9sk7
> > .
> 
> ## 
> 
> ______________________________________________Norbert Nemec
>         Aignerstr. 26 ... 81541 München ... Germany
>       Tel: +49-89-18944209  Mobile: +49-176-5502 5643
>              eMail:  Norbert@Nemec-online.de Norbert@Nemec-online.de

## 

______________________________________________Norbert Nemec
        Aignerstr. 26 ... 81541 München ... Germany
      Tel: +49-89-18944209  Mobile: +49-176-5502 5643
             eMail:  Norbert@Nemec-online.de Norbert@Nemec-online.de

**Comment by Murazaki** [comment]
The whole idea of this project was to make modifications on the QQuickList and have them be mirrored properly on the QObjectListModel, so most of the sync work is actually done by QQuickList.

But I have to admit that the QObjectListModel could be optimized. Since I was forcing pointer usage on the QQuickList, I didn't bother much about duplication on the QObjectListModel (those are duplicated pointers then).

**Comment by NNemec** [comment]
My concern was not just about an optimization but about a fundamental flaw, leading to data inconstencies:

QObjectListModel::setData will modifiy the data in QObjectListModel::m_data but not communicate the change back to QQuickList.

If you want to keep the model writeable from QML, the synchronization must be done in both directions. Getting this two-way communication correct is tricky and can easily be avoided by only keeping one copy of the data in the first place.
